- name: "Leitura de informações gerais de {{ id }}"
  ansible.builtin.include_role:
    name: utils
    tasks_from: services/gather_info

- name: "Setup de docker compose de {{ id }}"
  ansible.builtin.include_role:
    name: utils
    tasks_from: apps/compose_setup.yml
  when:
    - not (skip_compose is defined and skip_compose)

- name: "Garantia de registro de {{ id }}"
  ansible.builtin.include_role:
    name: utils
    tasks_from: apps/ensure_mapping.yml
  when:
    - not (skip_app_register is defined and skip_app_register)
